// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAakEF0SvbM-vcJqYJ7lZTb5wviaL1h5ns',
    appId: '1:879269238122:web:cc08a2b1c5992675c70113',
    messagingSenderId: '879269238122',
    projectId: 'loginjc-2023',
    authDomain: 'loginjc-2023.firebaseapp.com',
    storageBucket: 'loginjc-2023.appspot.com',
    measurementId: 'G-P1GT1LL3BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIkcueUiaJzy5cSQwZR6xifmVcgVokj7M',
    appId: '1:879269238122:android:24246a5a48380f14c70113',
    messagingSenderId: '879269238122',
    projectId: 'loginjc-2023',
    storageBucket: 'loginjc-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QRWnompSOu-H6lgDCh_lbRlRvVcSZTs',
    appId: '1:879269238122:ios:29ec0d8a47155c14c70113',
    messagingSenderId: '879269238122',
    projectId: 'loginjc-2023',
    storageBucket: 'loginjc-2023.appspot.com',
    iosBundleId: 'com.example.loginJc2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7QRWnompSOu-H6lgDCh_lbRlRvVcSZTs',
    appId: '1:879269238122:ios:37bdad5e3e0f1e18c70113',
    messagingSenderId: '879269238122',
    projectId: 'loginjc-2023',
    storageBucket: 'loginjc-2023.appspot.com',
    iosBundleId: 'com.example.loginJc2023.RunnerTests',
  );
}
